Bitly.Web/ViewModels/CreateLinkViewModel.cs
namespace Bitly.Web.ViewModels
{
    public class CreateLinkViewModel
    {
        public string Url { get; set; }
    }
}

Bitly.Web/ViewModels/LinkViewModel.cs
using System;

namespace Bitly.Web.ViewModels
{
    public class LinkViewModel
    {
        public long Id { get; set; }
        public string ShortUrl { get; set; }
        public string OriginalUrl { get; set; }
        public DateTime CreatedUtc { get; set; }
        public int VisitCount { get; set; }
    }
}

Bitly.Web/Controllers/Api/LinksController.cs
using Bitly.Business;
using Bitly.Entities;
using Bitly.Web.Services;
using Bitly.Web.ViewModels;
using System.Collections.Generic;
using System.Linq;
using System.Web.Http;

namespace Bitly.Web.Contollers.Api
{
    public class LinksController : ApiController
    {
        private ILinkManager _linkManager;
        private IConverter<Link, LinkViewModel> _linkToViewModelConverter;

        public LinksController(ILinkManager linkManager,
            IConverter<Link, LinkViewModel> linkToViewModelConverter)
        {
            _linkManager = linkManager;
            _linkToViewModelConverter = linkToViewModelConverter;
        }

        [HttpGet]
        [Route("api/links/list/{linkIds}")]
        public IEnumerable<LinkViewModel> GetLinksByIds(string linkIds)
        {
            var ids = linkIds.Split('-').Select(id => long.Parse(id)).ToArray();
            var links = _linkManager.GetLinks(ids);
            var viewModel = links.Select(link => _linkToViewModelConverter.Convert(link)).ToList();
            return viewModel;
        }

        [HttpPut]
        [Route("api/links")]
        public LinkViewModel CreateOrGet(CreateLinkViewModel createLinkViewModel)
        {
            if (!IsValidUrl(createLinkViewModel.Url))
            {
                return null;
            }

            var link = _linkManager.GetByOriginalUrl(createLinkViewModel.Url);
            if (link == null)
            {
                link = new Link
                {
                    OriginalUrl = createLinkViewModel.Url
                };
                _linkManager.Create(link);
            }

            var viewModel = _linkToViewModelConverter.Convert(link);
            return viewModel;
        }

        private bool IsValidUrl(string url)
        {
            return true;
        }


    }
}

Bitly.Web/Controllers/HomeController.cs
using Bitly.Business;
using System.Web.Mvc;

namespace Bitly.Web.Controllers
{
    public class HomeController : Controller
    {
        private ILinkManager _linkManager;

        public HomeController(ILinkManager linkManager)
        {
            _linkManager = linkManager;
        }

        public ActionResult Index()
        {
            var links = _linkManager.GetLinks(new long[] { 1, 2, 3, 4, 5 });
            return View(links);
        }
    }
}

Bitly.Web/Controllers/LinksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Bitly.Web.Controllers
{
	public class LinksController : Controller
	{
        public ActionResult Index()
        {
            return View();
        }
	}
}

Bitly.Web/Controllers/RedirectController.cs
using Bitly.Business;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Bitly.Web.Controllers
{
    public class RedirectController : Controller
    {
        private readonly ILinkManager _linkManager;

        public RedirectController(ILinkManager linkManager)
        {
            _linkManager = linkManager;
        }

        public ActionResult Index(string shortPath)
        {
            var link = _linkManager.GetWithVisitIncremention(shortPath);
            if (link == null)
            {
                return HttpNotFound();
            }

            return Redirect(link.OriginalUrl);
        }
    }
}

Bitly.Web/Views/Home/Index.cshtml
@model System.Collections.Generic.IEnumerable<Bitly.Entities.Link>
@{
    ViewBag.Title = "Homepage";
}
<div class="container" ng-app="bitlyApp">
    <div class="row">
        <div class="col-xs-12">
            <add-link></add-link>
        </div>
    </div>
</div>

Bitly.Web/Views/Links/Index.cshtml
<div class="container" ng-app="bitlyApp" ng-controller="UserLinksController">
    <div class="row">
        <div class="col-xs-12">
            <ul uib-pagination boundary-links="true"
                total-items="totalItems"
                ng-model="currentPage"
                items-per-page="itemsPerPage"
                ng-change="pageChanged()"
                class="pagination-sm"
                previous-text="&lsaquo;"
                next-text="&rsaquo;"
                first-text="&laquo;"
                last-text="&raquo;"></ul>
            <div ng-repeat="link in links" class="panel panel-default">
                <div class="panel-body">
                    Short Url: <a href="{{link.ShortUrl}}" target="_blank">{{link.ShortUrl}}</a>
                    <br />
                    Url: <a href="{{link.OriginalUrl}}" target="_blank">{{link.OriginalUrl}}</a>
                    <br />
                    Visit count: {{link.VisitCount}}
                </div>
            </div>
        </div>
    </div>
</div>

Bitly.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Poor Bitly Analogue - @ViewBag.Title</title>
        @Styles.Render("~/content/css")
    </head>
    <body>
        <nav class="navbar navbar-default">
            <div class="container">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="/">Poor Bitly Analogue</a>
                </div>

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li><a href="@Url.Action("Index", "Links")">My Links</a></li>
                    </ul>
                </div><!-- /.navbar-collapse -->
            </div><!-- /.container -->
        </nav>
        <br/>
        @RenderBody()
        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/angular")
    </body>
</html>